name = "ShowMethodTesting"
uuid = "aed2ae9c-e0a3-4a50-8068-bdeec279239a"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "1.2.1"

[deps]

[compat]
Aqua = "0.8.9"
julia = "1.9.0"
Test = "1.9.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
